api: uvicorn --port $PORT api:app --reload --root-path /api/v1
answers: uvicorn --port $PORT answersApi:app --reload --root-path /answers/v2
track: uvicorn --port $PORT trackApi:app --reload --root-path /track/v3