api: uvicorn --port $PORT api:app --reload
answers: uvicorn --port $PORT answersApi:app --reload
track: uvicorn --port $PORT trackApi:app --reload
state: uvicorn --port $PORT currentStateApi:app --reload
backend: uvicorn --port $PORT backend_for_frontend:app --reload